repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-merge-conflict
    - id: requirements-txt-fixer
    - id: mixed-line-ending
      args: [ --fix=lf ]
    - id: no-commit-to-branch
      args: [ --branch, master, --branch, develop ]
    - id: trailing-whitespace
      args: [ --markdown-linebreak-ext=md ]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      args: [--line-length=120]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: [--profile, black, --line-length=120]

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args: [-j=0, --max-line-length=120]
