# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    ports:
      - '33061:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
