version: '3.8'

services:
  nenaprasno_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nenaprasno
      MYSQL_USER: nenaprasno
      MYSQL_PASSWORD: nenaprasno

    ports:
      - '33061:3306'
    volumes:
      - /var/lib/mysql/

  mysql_adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'
