COMMAND_START = "start"
COMMAND_MENU = "menu"
COMMAND_TIMEZONE_CONFIGURATE = "get_timezone"
COMMAND_STATISTIC_MONTH = "mont_statistic"
COMMAND_STATISTIC_WEEK = "week_statitstic"
COMMAND_ACTUAL_REQUESTS = "actual_requests"
COMMAND_OVERDUE_REQUESTS = "overdue_requests"

COMMAND_REPEAT = "repeat_after_one_hour"
COMMAND_SEND_SOON = "send_soon"
COMMAND_ALREADY_SEND = "already_send"

IS_EXPERT_COMMAND = "is_expert_command"
NOT_EXPERT_COMMAND = "not_expert_command"
REGISTR_AS_EXPERT_COMMAND = "registr_as_expert_command"
SUPPORT_OR_CONSULT_COMMAND = "support_or_consult_command"
AFTER_REGISTR_MESSAGE_COMMAND = "after_registr_message_command"
TIMEZONE_COMMAND = "timezone_command"
SKIP_TIMEZONE_COMMAND = "skip_timezone_command"
