START_COMMAND = "start"
CANCEL_COMMAND = "cancel"
MENU_COMMAND = "menu"
TIMEZONE_CONFIGURATE_COMMAND = "get_timezone"
STATISTIC_MONTH_COMMAND = "mont_statistic"
STATISTIC_WEEK_COMMAND = "week_statitstic"
ACTUAL_REQUESTS_COMMAND = "actual_requests"
OVERDUE_REQUESTS_COMMAND = "overdue_requests"

REPEAT_COMMAND = "repeat_after_one_hour"
SEND_SOON_COMMAND = "send_soon"
ALREADY_SEND_COMMAND = "already_send"

IS_EXPERT_COMMAND = "is_expert_command"
NOT_EXPERT_COMMAND = "not_expert_command"
REGISTR_AS_EXPERT_COMMAND = "registr_as_expert_command"
SUPPORT_OR_CONSULT_COMMAND = "support_or_consult_command"
AFTER_REGISTR_MESSAGE_COMMAND = "after_registr_message_command"
TIMEZONE_COMMAND = "timezone_command"
SKIP_TIMEZONE_COMMAND = "skip_timezone_command"
