UNAUTHORIZED_STATE = "unauthorized_state"
REGISTRATION_STATE = "registration_state"
NEW_EXPERT_STATE = "new_expert_state"
TIMEZONE_STATE = "timezone_state"
MENU_STATE = "menu_state"
TIMEZONE_SET_STATE = "timezone_set_state"
TIMEZONE_GET_STATE = "timezone_get_state"
