name: Check bot productivity

on:
  push:
    types:
      - opened
    branches:
      - develop
  pull_request:
    types:
      - opened
    branches:
      - develop


jobs:
  build_and_run_bot:
    name: Startup bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start the bot
        env:
          TELEGRAM_TOKEN: ${{ env.TELEGRAM_TOKEN }}
        run: |
          python3 src/run_bot.py & sleep 15 && pkill -9 python
          python3 src/run_webhook_api.py & sleep 15 && pkill -9 python
