name: codestyle with PEP8

on:
   pull_request:
    branches:
      - develop
      - master


jobs:
  codestyle:
    name: Check codestyle PEP8
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v2
    -
      name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return
        pip install black
        pip install -r requirements.txt
    -
      name: Test with flake8
      run: |
        python -m flake8
    -
      name: Codestyle by black
      run: black --check .
