name: ask_nenaprasno_bot_deploy_on_stage

on:
  push:
    branches:
      - feature/deploy_stage
  pull_request:
    branches:
      - develop
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nenaprasno-ask-bot
  DEPLOY_PATH: /opt/develop/ask-bot
  REP_OWNER: studio-yandex-practicum

defaults:
  run:
    working-directory: .

jobs:
  check_if_merged:
    if: github.event.pull_request.merged == true
    name: Check if the pull request was not merged to the branch
    runs-on: ubuntu-latest
    steps:
      - name: Confirm that is it merged
        run: echo "Merged"

  build_and_push:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    needs: check_if_merged
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          labels: runnumber=${GITHUB_RUN_ID}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REP_OWNER }}/${{ env.IMAGE_NAME }}:stage,
            ${{ env.REGISTRY }}/${{ env.REP_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: Stage
    needs: build_and_push
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Copy docker-compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "infrastructure/docker-compose.stage.yaml"
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1
      - name: Create .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            sudo rm -f .env
            touch .env
            echo TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} >> .env
            echo APPLICATION_URL=${{ secrets.APPLICATION_URL }} >> .env
            echo SECRET_TELEGRAM_TOKEN=${{ secrets.SECRET_TELEGRAM_TOKEN }} >> .env

            echo WEEKLY_STAT_TIME=${{ secrets.WEEKLY_STAT_TIME }} >> .env
            echo WEEKLY_STAT_WEEK_DAYS=${{ secrets.WEEKLY_STAT_WEEK_DAYS }} >> .env
            echo MONTHLY_STAT_TIME=${{ secrets.MONTHLY_STAT_TIME }} >> .env
            echo MONTHLY_STAT_DAY=${{ secrets.MONTHLY_STAT_DAY }} >> .env

            echo MONTHLY_RECEIPT_REMINDER_TIME=${{ secrets.MONTHLY_RECEIPT_REMINDER_TIME }} >> .env
            echo MONTHLY_RECEIPT_REMINDER_DAY=${{ secrets.MONTHLY_RECEIPT_REMINDER_DAY }} >> .env

            echo DAYLY_COLLECT_CONSULTATIONS_TIME=${{ secrets.DAYLY_COLLECT_CONSULTATIONS_TIME }} >> .env
            echo DAILY_CONSULTATIONS_REMINDER_TIME=${{ secrets.DAILY_CONSULTATIONS_REMINDER_TIME }} >> .env

            echo URL_ASK_NENAPRASNO=${{ secrets.URL_ASK_NENAPRASNO }} >> .env
            echo URL_ASK_NENAPRASNO_API=${{ secrets.URL_ASK_NENAPRASNO_API }} >> .env
            echo SITE_API_BOT_TOKEN=${{ secrets.SITE_API_BOT_TOKEN }} >> .env
            echo TRELLO_BORD_ID=${{ secrets.TRELLO_BORD_ID }} >> .env

  start_application:
    name: Start application
    runs-on: ubuntu-latest
    environment:
      name: Stage
    needs: deploy
    steps:
      - name: Start appication
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}

            sudo docker image prune -f
            sudo docker pull ${{ env.REGISTRY }}/${{ env.REP_OWNER }}/${{ env.IMAGE_NAME }}:stage
            sudo docker compose --file docker-compose.stage.yaml stop
            sudo docker compose --file docker-compose.stage.yaml rm bot -f
            sudo docker compose --file docker-compose.stage.yaml up -d
