name: ask_nenaprasno_bot_deploy

on:
  pull_request:
    branches:
      - develop
    types: [closed]
  push:
    branches:
      - feature/test-deploy

jobs:
  build_and_push_ask_nenaprasno_bot_image:
    if: github.event.pull_request.merged == true
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ask_nenaprasno_bot:latest

  prepare_infrastructure:
    if: github.event.pull_request.merged == true
    name: Prepare Infrastructure
    runs-on: ubuntu-latest
    needs: build_and_push_ask_nenaprasno_bot_image
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Copy infrastructure directory to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: infrastructure/
          remote: code/
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_KEY }}
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd code/nginx
            sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
            sed -i "s+{{ROBOTS_FULL_PATH}}+$(pwd)+g" nginx.conf
            sed -i 's/{{IP}}/${{ secrets.IP }}/g' nginx.conf
            sed -i 's/{{DOMAIN}}/${{ secrets.DOMAIN }}/g' nginx.conf
            sed -i 's/{{BOT_PORT}}/${{ secrets.BOT_PORT }}/g' nginx.conf
            sudo cp nginx.conf /etc/nginx/sites-available/default
            sudo systemctl reload nginx

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: prepare_infrastructure
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd code
            sudo rm -f .env
            touch .env
            echo TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} >> .env
            echo BOT_PORT=${{ secrets.BOT_PORT }} >> .env
            echo WEBHOOK_URL=${{ secrets.WEBHOOK_URL }} >> .env
            echo HOST=${{ secrets.HOST }} >> .env
            echo SECRET_TELEGRAM_TOKEN=${{ secrets.SECRET_TELEGRAM_TOKEN }} >> .env
            echo WEEKLY_STAT_TIME=${{ secrets.WEEKLY_STAT_TIME }} >> .env
            echo WEEKLY_STAT_WEEK_DAYS=${{ secrets.WEEKLY_STAT_WEEK_DAYS }} >> .env
            echo MONTHLY_STAT_TIME=${{ secrets.MONTHLY_STAT_TIME }} >> .env
            echo MONTHLY_STAT_DAY=${{ secrets.MONTHLY_STAT_DAY }} >> .env
            echo MONTHLY_RECEIPT_REMINDER_TIME=${{ secrets.MONTHLY_RECEIPT_REMINDER_TIME }} >> .env
            echo MONTHLY_RECEIPT_REMINDER_DAY=${{ secrets.MONTHLY_RECEIPT_REMINDER_DAY }} >> .env
            echo DAYLY_COLLECT_CONSULTATIONS_TIME=${{ secrets.DAYLY_COLLECT_CONSULTATIONS_TIME }} >> .env
            echo DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS=${{ secrets.DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS }} >> .env
            echo BOT_PERSISTENCE_FILE=${{ secrets.BOT_PERSISTENCE_FILE }} >> .env
            echo SITE_API_URL=${{ secrets.SITE_API_URL }} >> .env
            echo IS_FAKE_API=${{ secrets.IS_FAKE_API }} >> .env
            echo SITE_API_BOT_TOKEN=${{ secrets.SITE_API_BOT_TOKEN }} >> .env
            echo LOG_NAME=${{ secrets.LOG_NAME }} >> .env
            echo TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }} >> .env
            echo TRELLO_ID_MODEL=${{ secrets.TRELLO_ID_MODEL }} >> .env
            echo TRELLO_TOKEN=${{ secrets.TRELLO_TOKEN }} >> .env
            echo TRELLO_BORD_ID=${{ secrets.TRELLO_BORD_ID }} >> .env
            echo URL_ASK_NENAPRASNO=${{ secrets.URL_ASK_NENAPRASNO }} >> .env

            sudo docker image prune -f
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ask_nenaprasno_bot:latest
            sudo docker-compose stop
            sudo docker-compose rm bot -f
            sudo docker-compose up -d
