name: Copy infrastructure files

on:
  push:
    branches:
      - feature/docker-compose-copy

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy infrastructure directory to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: infrastructure/docker-compose.yaml
          remote: code/infrastructure/docker-compose-serv.yaml
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
