name: Copy infrastructure files

on:
  push:
    branches:
      - feature/docker-compose-copy

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Copy infrastructure directory to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: setup.cfg
          remote: setup.cfg
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_KEY }}
